// <auto-generated />
namespace TP.EntityFrameworkCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addUserGuid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addUserGuid));
        
        string IMigrationMetadata.Id
        {
            get { return "201711260515233_addUserGuid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
